version: '3'
volumes:
  db_data:
services:
  postgres:
    image: kartoza/postgis:12.0
    restart: always
    volumes:
      - db_data:/var/lib/postgresql_data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
    - 5432:5432
  graphql-engine:
    image: hasura/graphql-engine:v1.3.0
    ports:
      - 5434:5434
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://admin:admin@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    ports:
      - 5433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin